### ISSUE TITLE
Behavior to debug. 

### ISSUE THREAD

**Issue by adi-lb-phoenix** [chsasank/llama.lisp#53] opened 2024-06-26 07:49 UTC
Command to execute : 
```
guile ../../utils/sexp-json.scm < matrix_multiplication.sexp | python3 ../../c-lisp.py | python3 ../../brilisp.py |python3 ../../llvm.py | bash ../brilisp/run.sh 
```
output 1
```
0.000000
0.000000
51122.500000
51122.500000
51122.500000
51122.500000
51122.500000
51122.500000
51122.500000
51122.500000
0.000000
0.000000
0.000000
0.000000
0.000000
0.000000
0.000000
0.000000
0.000000
0.000000
0.000000
0.000000
0.000000
0.000000
0.000000
0.000000
0.000000
0.000000
0.000000
0.000000
0.000000
0.000000
0.000000
0.000000
0.000000
0.000000
0.000000
0.000000
0.000000
0.000000
0.000000
0.000000
0.000000
0.000000
0.000000
0.000000
0.000000
0.000000
0.000000
0.000000
0.000000
-0.000000
0.000000
0.000000
0.000000
0.000000
0.000000
0.000000
0.000000
0.000000
0.000000
0.000000
0.000000
0.000000
0.000000
0.000000
0.000081
0.000000
0.000000
0.000000
0.000000
0.000000
0.000000
0.000000
0.000000
0.000000
-87377254397831510301065506891759616.000000
0.000000
0.000081
0.000000
0.000000
0.000000
-0.000000
0.000000
-0.000000
0.000000
0.000000
0.000000
0.000000
0.000000
-1.843628
0.000000
-0.000000
0.000000
0.000000
0.000000
0.000000
0.000000
-87417977673363842170588588482232320.000000
0.000000
```
repeating pattern 
```
51122.500000
51122.500000
51122.500000
51122.500000
51122.500000
51122.500000
51122.500000
51122.500000
```
similar behavior is observed https://github.com/chsasank/llama.lisp/issues/47  https://github.com/chsasank/llama.lisp/issues/46

**Comment by GlowingScrewdriver** [comment] 2024-06-26 13:12
We're seeing this with uninitialized arrays... So is it really a problem?

**Comment by GlowingScrewdriver** [comment] 2024-06-26 16:22
Duplicate of #46

**Comment by chsasank** [comment] 2024-06-30 16:21
We need more descriptive issue names.

**Closed by chsasank** 2024-06-30 16:21 UTC
